version: '3.1'

services:
  mariadb_usrs:
    image: mariadb:10.3
    container_name: mariadb_usrs
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: usuarios

  phpmyadmin_usrs:
    image: phpmyadmin
    container_name: phpmyadmin_usrs
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb_usrs

  usuarios:
    image: 'usuarios:latest'
    container_name: usuarios
    restart: always
    build:
      context: .
    depends_on:
      - mariadb_usrs
      - phpmyadmin_usrs
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb_usrs:3306/usuarios?useSSL=false

